package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestAddDeviceSubcommand exercises the real CLI surface: it builds the binary
// and runs `cc-mysub add-device`, verifying the subcommand dispatch, flag
// parsing, CA establishment, and the devices.json side effect all work together
// in the compiled binary. Post-收口 add-device only registers a fingerprint—it
// emits no wrapper (device onboarding is owned by install.sh).
func TestAddDeviceSubcommand(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}

	bin := filepath.Join(t.TempDir(), "cc-mysub")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}

	cfgDir := t.TempDir()
	cfgJSON := `{"listen":"127.0.0.1:8788","client":{"public_host":"ccapi.example.com","subscription_type":"max"}}`
	if err := os.WriteFile(filepath.Join(cfgDir, "config.json"), []byte(cfgJSON), 0o644); err != nil {
		t.Fatal(err)
	}

	const deviceFP = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
	cmd := exec.Command(bin, "add-device",
		"--config-dir", cfgDir, "--label", "phone", "--fingerprint", deviceFP)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("add-device: %v\n%s", err, out)
	}
	if !strings.Contains(string(out), deviceFP) {
		t.Errorf("output missing registered fingerprint:\n%s", out)
	}

	devices, err := os.ReadFile(filepath.Join(cfgDir, "devices.json"))
	if err != nil {
		t.Fatalf("devices.json not written: %v", err)
	}
	if !strings.Contains(string(devices), `"label": "phone"`) {
		t.Errorf("devices.json missing phone entry:\n%s", devices)
	}
	if !strings.Contains(string(devices), `"cert_sha256": "`+deviceFP+`"`) {
		t.Errorf("devices.json missing cert_sha256:\n%s", devices)
	}

	// 首次 add-device 须生成 cc-mysub 自有 CA。
	if _, err := os.Stat(filepath.Join(cfgDir, "ca.crt")); err != nil {
		t.Errorf("ca.crt not generated by add-device: %v", err)
	}
	if _, err := os.Stat(filepath.Join(cfgDir, "ca.key")); err != nil {
		t.Errorf("ca.key not generated by add-device: %v", err)
	}

	// 收口后 add-device 绝不产出 myclaude wrapper 文件 (分发改由 install.sh 管)。
	if m, _ := filepath.Glob(filepath.Join(cfgDir, "myclaude*")); len(m) > 0 {
		t.Errorf("add-device must not emit a wrapper file, found %v", m)
	}
}

// TestAddDeviceRequiresLabel verifies the contract surfaces as a non-zero exit.
func TestAddDeviceRequiresLabel(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}
	bin := filepath.Join(t.TempDir(), "cc-mysub")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}
	cfgDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(cfgDir, "config.json"),
		[]byte(`{"client":{"public_host":"h","frps_ip":"1.2.3.4","subscription_type":"max"}}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := exec.Command(bin, "add-device", "--config-dir", cfgDir).Run(); err == nil {
		t.Error("expected non-zero exit when --label is missing")
	}
}
