package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const fakeSha256Sums = "" +
	"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  cc-mysub-linux-amd64\n" +
	"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb  cc-mysub-linux-arm64\n" +
	"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc  cc-mysub-darwin-amd64\n" +
	"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  cc-mysub-darwin-arm64\n"

// TestAddDeviceSubcommand exercises the real CLI surface: it builds the binary
// and runs `cc-mysub add-device`, verifying the subcommand dispatch, flag
// parsing, the go:embed'd wrapper template, and devices.json side effect all
// work together in the compiled binary.
func TestAddDeviceSubcommand(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}

	bin := filepath.Join(t.TempDir(), "cc-mysub")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}

	cfgDir := t.TempDir()
	cfgJSON := `{"listen":"127.0.0.1:8788","client":{"public_host":"ccapi.example.com","subscription_type":"max"}}`
	if err := os.WriteFile(filepath.Join(cfgDir, "config.json"), []byte(cfgJSON), 0o644); err != nil {
		t.Fatal(err)
	}
	wrapper := filepath.Join(t.TempDir(), "myclaude-phone")

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/SHA256SUMS") {
			io.WriteString(w, fakeSha256Sums)
			return
		}
		http.NotFound(w, r)
	}))
	defer srv.Close()

	const deviceFP = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
	cmd := exec.Command(bin, "add-device",
		"--config-dir", cfgDir, "--label", "phone", "--fingerprint", deviceFP, "--release", "v1.0.0", "--out", wrapper)
	cmd.Env = append(os.Environ(), "CC_MYSUB_RELEASE_BASE_URL="+srv.URL)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("add-device: %v\n%s", err, out)
	}
	if !strings.Contains(string(out), deviceFP) {
		t.Errorf("output missing registered fingerprint:\n%s", out)
	}

	devices, err := os.ReadFile(filepath.Join(cfgDir, "devices.json"))
	if err != nil {
		t.Fatalf("devices.json not written: %v", err)
	}
	if !strings.Contains(string(devices), `"label": "phone"`) {
		t.Errorf("devices.json missing phone entry:\n%s", devices)
	}
	if !strings.Contains(string(devices), `"cert_sha256": "`+deviceFP+`"`) {
		t.Errorf("devices.json missing cert_sha256:\n%s", devices)
	}

	// 首次 add-device 须生成 cc-mysub 自有 CA。
	if _, err := os.Stat(filepath.Join(cfgDir, "ca.crt")); err != nil {
		t.Errorf("ca.crt not generated by add-device: %v", err)
	}
	if _, err := os.Stat(filepath.Join(cfgDir, "ca.key")); err != nil {
		t.Errorf("ca.key not generated by add-device: %v", err)
	}

	w, err := os.ReadFile(wrapper)
	if err != nil {
		t.Fatalf("wrapper not written: %v", err)
	}
	// mTLS 形态: 断言 helper exec 行(--host/--client-cert/--client-key) + NODE_EXTRA_CA_CERTS;
	// 通用 wrapper 不含 per-device token/指纹。
	if !strings.Contains(string(w), `PUBLIC_HOST="ccapi.example.com"`) {
		t.Errorf("wrapper not filled from config:\n%s", w)
	}
	if !strings.Contains(string(w), `exec "$CC_MYSUB_BIN" helper --host "$PUBLIC_HOST" --client-cert "$DEV_CERT" --client-key "$DEV_KEY"`) {
		t.Errorf("wrapper missing mTLS helper exec line:\n%s", w)
	}
	if !strings.Contains(string(w), `NODE_EXTRA_CA_CERTS="$CA_CERT"`) {
		t.Errorf("wrapper missing NODE_EXTRA_CA_CERTS:\n%s", w)
	}
	if strings.Contains(string(w), "DEVICE_TOKEN") || strings.Contains(string(w), deviceFP) {
		t.Errorf("fleet-generic wrapper must not carry per-device token/fingerprint:\n%s", w)
	}

	// 通用 wrapper 内联 CA 公证书(非私钥)，仍保持 0o700：owner 可执行（放入 PATH 直接调用），
	// group/other 无权（沿用既有权限纪律）。
	if fi, err := os.Stat(wrapper); err != nil {
		t.Fatalf("stat wrapper: %v", err)
	} else if perm := fi.Mode().Perm(); perm != 0o700 {
		t.Errorf("wrapper mode = %#o want 0o700", perm)
	}
}

// TestAddDeviceRequiresLabel verifies the contract surfaces as a non-zero exit.
func TestAddDeviceRequiresLabel(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}
	bin := filepath.Join(t.TempDir(), "cc-mysub")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, out)
	}
	cfgDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(cfgDir, "config.json"),
		[]byte(`{"client":{"public_host":"h","frps_ip":"1.2.3.4","subscription_type":"max"}}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := exec.Command(bin, "add-device", "--config-dir", cfgDir).Run(); err == nil {
		t.Error("expected non-zero exit when --label is missing")
	}
}
